title:               Simplifying Assumptions
description:         "the only winning move is not to play"
markdown: kramdown
theme: jekyll-theme-midnight
permalink:           pretty
relative_permalinks: false
paginate:            5
gems: [jekyll-paginate]
paginate_path: "page:num"
