# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false
paginate:            5
gems: [jekyll-paginate]
paginate_path: "page:num"

# Setup
title:               Simplifying Assumptions
description:         "the only winning move is not to play"
base-url:             "base-url"
baseurl:             ""
url:                 "https://cooijmanstim.github.io"
github:              "https://www.github.com/cooijmanstim"
timezone:            UTC

# Custom vars
version:             0.0.1

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight
